Repository hyosung-final-team2/final-project, pull requests merged in 2024-07, with the labels that each got.

#13 KAN-39 feat: 주문 모달 구현
  ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx
  ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/ModalCustomTheme.js
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailModal.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SingleOrderProduct.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SubScriptionOrderProduct.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx
  ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx
  ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableFeature.jsx
  ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableRow.jsx
  ubun2_fe/src/customer/components/common/Alert/Alert.jsx
  ubun2_fe/src/customer/components/common/Select/Select.jsx
  ubun2_fe/tailwind.config.js
Labels: FE

#15 Kan 33 feature/front address search popup
  ubun2_fe/package-lock.json
  ubun2_fe/package.json
  ubun2_fe/src/App.jsx
  ubun2_fe/src/customer/api/addressApi.js
  ubun2_fe/src/customer/components/AddressList/MemberAddressEditModal.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx
  ubun2_fe/src/customer/components/common/AddressSearch/AddressSearchPopUp.jsx
  ubun2_fe/src/customer/components/common/Input/AddressInput.jsx
  ubun2_fe/src/customer/components/common/Input/InfoInput.jsx
Labels: FE

#17 Kan 67 feature/front member address edit modal
  ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressEditModal.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTable.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTableRow.jsx
  ubun2_fe/src/customer/components/MemberList/MemberInsertModal/AddressInfoSection/AddressInfoSection.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableFeature.jsx
  ubun2_fe/src/customer/components/common/Input/AddressInput.jsx
  ubun2_fe/src/customer/store/Address/useAddressStore.js
Labels: FE

#29 KAN-72-feature/back find all address
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/impl/AddressRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java
  ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressControllerTest.java
  ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/TestSecurityConfig.java
Labels: BE

#33 Kan-76-feat : 주문 목록 전체 조회
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SearchRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/UnifiedOrderResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/Order.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/SubscriptionOrder.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/exception/OrderException.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/exception/OrderExceptionType.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java
  ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerControllerTest.java
Labels: BE

#40 Kan 74 feature/back update delete address
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/address/AddressException.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/address/AddressExceptionType.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java
  ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressControllerTest.java
Labels: BE

#41 Kan-77-feat : 단건 주문 상세 조회
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/UnifiedOrderResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/Order.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/OrderProduct.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/SubscriptionOrderProduct.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java
  ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerControllerTest.java
Labels: BE

#43 Kan 85 feature/back payment method
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/AccountPaymentRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/AccountPaymentResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/CardPaymentRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/CardPaymentResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/MemberPaymentMethodsResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodDetailRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodDetailResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/AccountPayment.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/CardPayment.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/exception/paymentMethod/PaymentMethodException.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/exception/paymentMethod/PaymentMethodExceptionType.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/impl/PaymentMethodRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java
  ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodControllerTest.java
Labels: BE

#50 Kan 85 feature/back payment method
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/response/MemberDetailResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/AccountPaymentResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/CardPaymentResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/MemberPaymentMethodsResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodDetailResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/impl/PaymentMethodRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java
Labels: BE

#51 KAN-85 refactor: 결제수단 전체 조회에 불필요한 memberId 파라미터 제거
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/AccountPaymentRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/CardPaymentRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/impl/PaymentMethodRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java
Labels: BE

#54 Kan-90 feature: 주문 목록 API 연동
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderDetailProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderDetailResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java
  ubun2_be/src/main/resources/db/data.sql
  ubun2_fe/src/customer/api/Order/OrderList/OrderModal/orderModal.js
  ubun2_fe/src/customer/api/Order/OrderList/OrderModal/queris.js
  ubun2_fe/src/customer/api/Order/OrderList/OrderTable/orderTable.js
  ubun2_fe/src/customer/api/Order/OrderList/OrderTable/queris.js
  ubun2_fe/src/customer/api/Order/OrderList/SubscriptionOrderModal/subscriptionOrderModal.js
  ubun2_fe/src/customer/components/OrderList/OrderDetailData.js
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailInfo.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailModal.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderPaymentAccount.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderPaymentCard.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SingleOrderProduct.jsx
  ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SubScriptionOrderProduct.jsx
  ubun2_fe/src/customer/components/OrderList/OrderListData.js
  ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx
  ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableFeature.jsx
  ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx
  ubun2_fe/src/customer/components/common/Table/UnifiedOrderTableBody.jsx
  ubun2_fe/src/customer/components/common/Table/tableIndex.js
  ubun2_fe/src/customer/pages/internal/OrderList.jsx
Labels: BE, FE

#62 Kan 86 feature/front address
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/impl/AddressRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/impl/PaymentMethodRepositoryImpl.java
  ubun2_fe/src/customer/api/Address/AddressModal/addressModal.js
  ubun2_fe/src/customer/api/Address/AddressModal/queris.js
  ubun2_fe/src/customer/api/Address/AddressTable/queris.js
  ubun2_fe/src/customer/api/Address/AddressTable/registerAddress.js
  ubun2_fe/src/customer/api/PaymentMethod/Modal/paymentMethodModal.js
  ubun2_fe/src/customer/api/PaymentMethod/Modal/queris.js
  ubun2_fe/src/customer/api/PaymentMethod/Table/queris.js
  ubun2_fe/src/customer/api/PaymentMethod/Table/registerPayment.js
  ubun2_fe/src/customer/components/AddressList/AddressARegistrationModal.jsx
  ubun2_fe/src/customer/components/AddressList/AddressListData.js
  ubun2_fe/src/customer/components/AddressList/AddressTable.jsx
  ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTable.jsx
  ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTableRow.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentTable/MemberPaymentTable.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentTable/MemberPaymentTableRow.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentInfo.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTable.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableRow.jsx
  ubun2_fe/src/customer/components/common/Info/MemberInfo.jsx
  ubun2_fe/src/customer/components/common/Input/AddressInput.jsx
  ubun2_fe/src/customer/pages/internal/AddressList.jsx
  ubun2_fe/src/customer/store/Address/useAddressStore.js
  ubun2_fe/src/customer/store/PaymentMethod/paymentMethodStore.js
Labels: FE

#68 Kan 86 feature/front address
  ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx
  ubun2_fe/src/customer/components/common/Modal/ConfirmationModal.jsx
  ubun2_fe/src/customer/components/common/Modal/icons.jsx
  ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx
Labels: FE

#75 KAN-109 feat: 공통 버튼&하단 모달 컴포넌트 구현
  ubun2_fe/src/member/components/common/SlideUpModal.jsx
  ubun2_fe/src/member/components/common/button/BottomButton.jsx
Labels: FE, 기능

#89 Kan 110 feature/front member payments
  ubun2_fe/src/assets/images/KB.svg
  ubun2_fe/src/assets/images/arrow.svg
  ubun2_fe/src/assets/images/bc.svg
  ubun2_fe/src/assets/images/card.svg
  ubun2_fe/src/assets/images/hana.svg
  ubun2_fe/src/assets/images/hyundai.svg
  ubun2_fe/src/assets/images/kakao.svg
  ubun2_fe/src/assets/images/kbank.svg
  ubun2_fe/src/assets/images/logo/bc.svg
  ubun2_fe/src/assets/images/logo/hana.svg
  ubun2_fe/src/assets/images/logo/hyundai.svg
  ubun2_fe/src/assets/images/logo/kb.svg
  ubun2_fe/src/assets/images/logo/lotte.svg
  ubun2_fe/src/assets/images/logo/master.svg
  ubun2_fe/src/assets/images/logo/nonghyup.svg
  ubun2_fe/src/assets/images/logo/samsung.svg
  ubun2_fe/src/assets/images/logo/shinhan.svg
  ubun2_fe/src/assets/images/logo/visa.svg
  ubun2_fe/src/assets/images/logo/woori.svg
  ubun2_fe/src/assets/images/lotte.svg
  ubun2_fe/src/assets/images/nonghyup.svg
  ubun2_fe/src/assets/images/png/bc.png
  ubun2_fe/src/assets/images/png/hana.png
  ubun2_fe/src/assets/images/png/hyundai.png
  ubun2_fe/src/assets/images/png/kakao.png
  ubun2_fe/src/assets/images/png/kb.png
  ubun2_fe/src/assets/images/png/kbank.png
  ubun2_fe/src/assets/images/png/lotte.png
  ubun2_fe/src/assets/images/png/nonghyup.png
  ubun2_fe/src/assets/images/png/samsung.png
  ubun2_fe/src/assets/images/png/shinhan.png
  ubun2_fe/src/assets/images/png/toss.png
  ubun2_fe/src/assets/images/png/woori.png
  ubun2_fe/src/assets/images/samsung.svg
  ubun2_fe/src/assets/images/samsungcard.svg
  ubun2_fe/src/assets/images/sc.svg
  ubun2_fe/src/assets/images/shinhan.svg
  ubun2_fe/src/assets/images/toss.svg
  ubun2_fe/src/assets/images/woori.svg
  ubun2_fe/src/member/components/PaymentMethod/AccountForm.jsx
  ubun2_fe/src/member/components/PaymentMethod/CardForm.jsx
  ubun2_fe/src/member/components/PaymentMethod/CardItem.jsx
  ubun2_fe/src/member/components/PaymentMethod/CardList.jsx
  ubun2_fe/src/member/components/PaymentMethod/CreditCard.jsx
  ubun2_fe/src/member/components/PaymentMethod/MyPageCardItem.jsx
  ubun2_fe/src/member/components/PaymentMethod/PaymentItem.jsx
  ubun2_fe/src/member/components/common/SlideUpModal.jsx
  ubun2_fe/src/member/components/common/input/FloatingLabelInput.jsx
  ubun2_fe/src/member/components/common/input/InfoInput.jsx
  ubun2_fe/src/member/layouts/PageContent.jsx
  ubun2_fe/src/member/pages/internal/ChoosePayment.jsx
  ubun2_fe/src/member/pages/internal/EditPayment.jsx
  ubun2_fe/src/member/pages/internal/MyPaymentsList.jsx
  ubun2_fe/tailwind.config.js
Labels: FE

#92 KAN-147 feat: 회원의 주소지 관련 기능 api 구현
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/MemberAddressController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/AddressExceptionType.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MyAddressResponse.java
Labels: BE, 기능

#111 KAN-166 feat: 장바구니에 제품 추가
  ubun2_fe/src/assets/images/check.svg
  ubun2_fe/src/member/api/Cart/cart.js
  ubun2_fe/src/member/api/Cart/queris.js
  ubun2_fe/src/member/pages/internal/Product.jsx
Labels: FE

#114 Kan 179 feature/back pushnotification
  ubun2_be/.gitignore
  ubun2_be/build.gradle
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/config/FirebaseConfig.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/FcmMessage.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/GroupAlarmSendRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/PersonalAlarmSendRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/FcmTokenRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MemberSignUpRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberCustomerRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java
  ubun2_fe/public/firebase-messaging-sw.js
  ubun2_fe/src/FCMTokenStore.js
  ubun2_fe/src/customer/api/common/Login/queris.js
  ubun2_fe/src/member/api/FcmToken/fcmToken.js
  ubun2_fe/src/member/api/FcmToken/queris.js
  ubun2_fe/src/member/api/Register/queris.js
  ubun2_fe/src/member/pages/internal/StoreList.jsx
Labels: BE

#116 Kan 182 feature/back alarmsave
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/entity/Alarm.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/repository/AlarmRedisRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberCustomerRepository.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java
Labels: BE

#133 Kan 198 feature/front dashboard api
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderSummaryResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/SubscriptionOrderProductResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/UnifiedOrderResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/DashboardService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/impl/DashboardServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
  ubun2_fe/src/customer/components/Dashboard/DashboardAreaChart.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardIndex.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashBoardLineChart.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardPieChart.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardStats.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardTopBar.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrders.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrdersTableRow.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/SidoMap.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodAccount.jsx
  ubun2_fe/src/member/store/address/AddressStore.js
  ubun2_fe/tailwind.config.js
Labels: FE

#157 Kan 198 feat/front dashboard api
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java
  ubun2_fe/src/member/api/Payment/payments.js
  ubun2_fe/src/member/api/Payment/queries.js
  ubun2_fe/src/member/components/PaymentMethod/PasswordKeypad.jsx
  ubun2_fe/src/member/layouts/PageContent.jsx
  ubun2_fe/src/member/pages/internal/InputPassword.jsx
  ubun2_fe/src/member/pages/internal/MyPaymentsList.jsx
  ubun2_fe/src/member/store/Payment/PaymentStore.js
Labels: BE, FE, 기능

#197 Kan 200 refactor/front dashboard
  ubun2_fe/src/customer/api/PaymentMethod/Table/queris.js
  ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressMap.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTable.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableFeature.jsx
  ubun2_fe/src/customer/components/PaymentMethodList/Skeleton/SkeletonPaymentMethodTableFeature.jsx
  ubun2_fe/src/customer/components/common/Input/AddressInput.jsx
  ubun2_fe/src/customer/components/common/ToggleButon/ToggleButton.jsx
  ubun2_fe/src/customer/utils/accountFormat.js
  ubun2_fe/src/customer/utils/cardFormat.js
  ubun2_fe/src/customer/utils/dateFormat.js
  ubun2_fe/src/member/components/common/input/InfoInput.jsx
Labels: FE

#209 KAN-200 fix: 대시보드 주문 목록 & 맵 수정
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/UnifiedOrderResponse.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
  ubun2_fe/src/customer/components/Dashboard/DashboardIndex.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardAreaChart.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrdersTableRow.jsx
  ubun2_fe/src/customer/components/Dashboard/DashboardItem/SidoMap.jsx
Labels: FE

#210 Kan 239 feature/back member
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/MemberAddressController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/MemberAddressRegisterRequest.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/entity/Address.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/MemberPaymentMethodController.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/AccountPayment.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/CardPayment.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java
  ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java
Labels: BE, 기능
